-- Reference data: plans, advisor templates, feature flags, demo institution and synthetic profiles.
-- Everything here is synthetic and labelled as such.

insert into institutions (slug, name, is_demo) values
  ('demo-university', 'Demo University (synthetic)', true)
on conflict (slug) do nothing;

-- ---------------------------------------------------------------- billing plans (PRD: Proposed Customer Plans)
insert into billing_plans (code, name, description, price_inr_paise, price_usd_cents, period_days,
                           voice_minutes, ai_requests, chat_messages, features, is_purchasable, sort_order) values
  ('waitlist_beta', 'Waitlist Beta', 'Free controlled beta for invited waitlist testers.', 0, 0, 90,
     5, 60, 300, '["Core web product","Synthetic demo profiles","Limited AI plans","One controlled voice check-in"]', false, 10),
  ('student_free', 'Student Free', 'Basic context, priority view, limited text guidance, one introductory check-in.', 0, 0, 30,
     3, 20, 60, '["Priority view","Limited text guidance","One introductory voice check-in"]', false, 20),
  ('sage_plus', 'SAGE Plus', 'Expanded planning with up to 10 included voice minutes.', 29900, 499, 30,
     10, 300, 1000, '["Expanded planning","Up to 10 voice minutes","Knowledge chatbot"]', true, 30),
  ('sage_pro', 'SAGE Pro', 'Advanced planning, deeper reviews, up to 30 included voice minutes.', 69900, 999, 30,
     30, 1000, 3000, '["Advanced planning","Deeper reviews","Up to 30 voice minutes"]', true, 40),
  ('campus_pilot', 'Campus Pilot', 'Up to 500 students, advisor workspace, 1,000-minute shared voice pool. Contact sales.', 4900000, 74900, 90,
     1000, 50000, 100000, '["Advisor workspace","Admin controls","Shared voice pool"]', false, 50)
on conflict (code) do nothing;

-- ---------------------------------------------------------------- feature flags
insert into feature_flags (key, enabled, description) values
  ('voice_calls', true, 'Allow users to request AI voice check-ins'),
  ('knowledge_chat', true, 'Enable the RAG knowledge chatbot'),
  ('payments_test_checkout', true, 'Enable Razorpay test-mode checkout'),
  ('professional_mode', true, 'Professional mode workflows'),
  ('founder_mode', true, 'Founder mode workflows'),
  ('open_signup', false, 'Allow sign-in by users who are not on the waitlist')
on conflict (key) do nothing;

-- ---------------------------------------------------------------- advisor templates (PRD Epic 6)
insert into advisor_templates (key, modes, category, title, description, help_types, prep_questions, share_checklist, sort_order) values
 ('course_faculty', '{student}', 'academic', 'Course Faculty',
  'The instructor for a specific course. Best for subject doubts, attendance conflicts tied to a course, and assessment clarifications.',
  '["Concept clarification","Attendance or timetable conflicts for the course","Assessment and deadline questions"]',
  '["Which topic or session exactly is the blocker?","What have you already tried?","What decision do you need from the instructor?"]',
  '["Course code and section","Attendance figure and dates missed","Specific question or request"]', 10),
 ('academic_advisor', '{student}', 'academic', 'Academic Advisor',
  'Helps with overall academic standing, workload balance, course selection, and recovery plans across subjects.',
  '["Workload and schedule balancing","Recovery plans","Elective and prerequisite planning"]',
  '["Which subjects are at risk and why?","What is your weekly availability?","What outcome would count as success this term?"]',
  '["Current grades and attendance summary","Upcoming deadlines","Your proposed plan"]', 20),
 ('placement_advisor', '{student}', 'career', 'Placement Advisor',
  'Connects coursework and skills to target roles, resume and interview readiness.',
  '["Role targeting","Resume review","Interview preparation"]',
  '["Which roles are you targeting?","Which skills feel weakest?","What is your timeline?"]',
  '["Target roles","Resume draft","Skills and projects list"]', 30),
 ('finance_office', '{student}', 'administrative', 'Finance Office',
  'Fee deadlines, payment plans, scholarships, and financial-aid paperwork.',
  '["Fee deadlines","Payment plans","Scholarship paperwork"]',
  '["Which fee or deadline is involved?","Is a payment plan needed?","What documents do you have?"]',
  '["Student ID","Fee notice","Supporting documents"]', 40),
 ('student_support', '{student,professional,founder}', 'wellbeing', 'Student Support / Wellbeing',
  'Non-academic support such as health-related absence, personal circumstances, and wellbeing resources. SAGE AI does not provide medical or mental-health care.',
  '["Health-related absence documentation","Personal circumstances","Wellbeing resources"]',
  '["What support would help most right now?","Is documentation available?","Is anything urgent?"]',
  '["Only what you are comfortable sharing","Relevant dates","Any documentation"]', 50),
 ('manager', '{professional}', 'career', 'Manager Conversation',
  'A structured conversation with your manager about learning time, growth goals, or role change.',
  '["Protected learning time","Growth goals","Internal mobility"]',
  '["What do you want your manager to agree to?","How does it benefit the team?","What is the timeline?"]',
  '["Goal summary","Proposed weekly time","Evidence of progress"]', 60),
 ('career_coach', '{professional}', 'career', 'Career Coach',
  'Role-transition strategy, positioning, and interview preparation.',
  '["Role transition","Positioning","Interview practice"]',
  '["What role and by when?","Which gaps are largest?","What has not worked so far?"]',
  '["Target role","Resume","Portfolio gaps"]', 70),
 ('subject_mentor', '{professional}', 'learning', 'Subject Mentor',
  'Deep help on a specific skill or certification.',
  '["Skill deep-dives","Certification prep","Portfolio feedback"]',
  '["Which topic is blocking you?","What resources are you using?","What is your exam or deadline date?"]',
  '["Course progress","Practice results","Specific questions"]', 80),
 ('founder_coach', '{founder}', 'venture', 'Founder Coach',
  'Weekly operating rhythm, prioritisation, and decision quality.',
  '["Prioritisation","Decision briefs","Operating cadence"]',
  '["What decision is stuck?","What evidence do you have?","What would change your mind?"]',
  '["Current milestone","Open decisions","Last week''s commitments"]', 90),
 ('domain_mentor', '{founder}', 'venture', 'Domain Mentor',
  'Industry-specific guidance for customers, distribution, and product.',
  '["Customer discovery","Go-to-market","Industry context"]',
  '["Who is the customer?","What have interviews shown?","What is the riskiest assumption?"]',
  '["Customer interview notes","Experiment results","Key metrics"]', 100),
 ('investor_prep_mentor', '{founder}', 'venture', 'Investor-Preparation Mentor',
  'Pitch narrative, fundraising readiness and investor Q&A practice.',
  '["Pitch narrative","Metrics story","Q&A practice"]',
  '["When is the pitch?","What is the ask?","Which questions do you fear most?"]',
  '["Deck","Metrics","Use of funds"]', 110),
 ('legal_finance_specialist', '{founder}', 'venture', 'Legal or Finance Specialist',
  'Incorporation, contracts, compliance, and financial planning questions.',
  '["Incorporation","Contracts","Compliance and runway planning"]',
  '["What document or decision is involved?","What is the deadline?","What is the risk if delayed?"]',
  '["Relevant documents","Deadlines","Specific question"]', 120)
on conflict (key) do nothing;

-- ---------------------------------------------------------------- synthetic demo profiles (PRD: Dynamic AI Proof)
-- Three students share the same visible attendance-risk signal but have different hidden causes.
insert into demo_profiles (key, mode, display_name, summary, profile, signals, hidden_context) values
 ('student_timetable_conflict', 'student', 'Aarav (demo) — timetable conflict',
  'Second-year BBA student below 75% attendance in Business Statistics.',
  '{"program":"BBA","semester":4,"subjects":["Business Statistics","Marketing Management","Organisational Behaviour","Financial Accounting"],
    "career_goal":"Product management internship","availability":"Weekday evenings, weekends",
    "notes":"Took a part-time campus job this term."}',
  '[{"type":"attendance","label":"Business Statistics attendance","subject":"Business Statistics","value_num":62,"threshold":75,"unit":"%"},
    {"type":"deadline","label":"Statistics problem set 3","subject":"Business Statistics","due_in_days":5},
    {"type":"grade","label":"Business Statistics mid-term","subject":"Business Statistics","value_num":71,"threshold":60,"unit":"%"},
    {"type":"attendance","label":"Marketing Management attendance","subject":"Marketing Management","value_num":88,"threshold":75,"unit":"%"}]',
  'The Tuesday/Thursday 9am statistics lecture clashes with a campus library job shift that started this term. The student understands the subject well (mid-term 71%) and wants to switch to the afternoon section or get the coordinator to approve a section change.'),
 ('student_subject_difficulty', 'student', 'Diya (demo) — subject difficulty',
  'Second-year BBA student below 75% attendance in Business Statistics with falling scores.',
  '{"program":"BBA","semester":4,"subjects":["Business Statistics","Marketing Management","Organisational Behaviour","Financial Accounting"],
    "career_goal":"Marketing analyst","availability":"Afternoons after 3pm"}',
  '[{"type":"attendance","label":"Business Statistics attendance","subject":"Business Statistics","value_num":61,"threshold":75,"unit":"%"},
    {"type":"grade","label":"Business Statistics mid-term","subject":"Business Statistics","value_num":38,"threshold":40,"unit":"%"},
    {"type":"exam","label":"Business Statistics end-term","subject":"Business Statistics","due_in_days":21},
    {"type":"deadline","label":"Statistics problem set 3","subject":"Business Statistics","due_in_days":5}]',
  'The student stopped attending because they feel lost since the hypothesis-testing unit and are embarrassed to ask questions in class. They avoid the lecture. They would benefit from a tutorial/office hours and a topic-by-topic recovery plan before the end-term.'),
 ('student_health_absence', 'student', 'Kabir (demo) — documented health absence',
  'Second-year BBA student below 75% attendance in Business Statistics after a medical absence.',
  '{"program":"BBA","semester":4,"subjects":["Business Statistics","Marketing Management","Organisational Behaviour","Financial Accounting"],
    "career_goal":"Finance / consulting","availability":"Flexible, recovering"}',
  '[{"type":"attendance","label":"Business Statistics attendance","subject":"Business Statistics","value_num":63,"threshold":75,"unit":"%"},
    {"type":"attendance","label":"Financial Accounting attendance","subject":"Financial Accounting","value_num":70,"threshold":75,"unit":"%"},
    {"type":"deadline","label":"Medical leave documentation window","due_in_days":7},
    {"type":"grade","label":"Business Statistics mid-term","subject":"Business Statistics","value_num":64,"threshold":40,"unit":"%"}]',
  'The student was hospitalised for dengue for twelve days and has a discharge summary and doctor''s certificate but has not submitted a medical-leave/attendance-condonation request. Main blocker is not knowing the process and the deadline. Health is now recovering.'),
 ('professional_upskilling', 'professional', 'Meera (demo) — data analyst to PM',
  'Working data analyst preparing for a product manager role change.',
  '{"target_role":"Associate Product Manager","skill_goals":["Product sense","SQL for product analytics","Stakeholder communication"],
    "courses":["PM fundamentals course — 40% complete"],"weekly_availability_hours":6,"portfolio_gaps":["No written product case study"]}',
  '[{"type":"interview","label":"APM interview loop","due_in_days":18},
    {"type":"course_progress","label":"PM fundamentals course","value_num":40,"threshold":80,"unit":"%"},
    {"type":"portfolio","label":"Product case study","value_text":"not started"}]',
  'Work deadlines consumed learning time for three weeks; needs protected time and a case-study plan before the interview.'),
 ('founder_discovery', 'founder', 'Rohan (demo) — pre-seed founder',
  'Pre-seed founder building a campus logistics product, pitch in 3 weeks.',
  '{"venture_stage":"pre-seed","current_milestone":"10 paying pilot customers","customer_questions":["Will hostels pay monthly?"],
    "experiments":["Pilot at 2 hostels"],"decisions":["Pricing model"]}',
  '[{"type":"milestone","label":"Paying pilot customers","value_num":3,"threshold":10,"unit":"customers"},
    {"type":"pitch","label":"Accelerator pitch","due_in_days":21},
    {"type":"customer_interviews","label":"Customer interviews this month","value_num":4,"threshold":15,"unit":"interviews"}]',
  'Founder has been building features instead of talking to customers; pricing decision is stuck.')
on conflict (key) do nothing;
